import assert from 'node:assert/strict';
import fs from 'node:fs';
import { P2_MOE_SKILL_SEQUENCE,P2_MOE_NUMBER1000_OBJECTIVES,curriculumSequenceFor,defaultState,ensureSkillState,skillsFor } from '../engine.mjs';
assert.deepEqual(curriculumSequenceFor('grade2').map(s=>s.id),P2_MOE_SKILL_SEQUENCE);
assert.ok(P2_MOE_SKILL_SEQUENCE.indexOf('moneyP2') < P2_MOE_SKILL_SEQUENCE.indexOf('lengthMetre2'));
assert.deepEqual(P2_MOE_NUMBER1000_OBJECTIVES.map(x=>x.code),['1.1','1.2','1.3','1.4','1.5','1.6']);
const state=defaultState(); state.profile='grade2'; skillsFor('grade2').forEach(s=>ensureSkillState(state,s.id)); const lc=ensureSkillState(state,'number1000').learningCycle;
assert.equal(lc.lessonStepIndex,0); assert.equal(lc.lessonTaughtAt,0);
const app=fs.readFileSync(new URL('../app.js',import.meta.url),'utf8'); const css=fs.readFileSync(new URL('../styles.css',import.meta.url),'utf8');
for(const id of ['ten-bundle','count-tens','count-hundreds','hundred-sense','model-build','place-value','same-digit','zero-place','read-write','word-build']) assert.ok(app.includes("id:'"+id+"'"),'missing '+id);
for(const copy of ['10 birlik = 1 onluk','10 onluk = 1 yüzlük','10 yüzlük = 1000','347 = 300 + 40 + 7','347 ↔ üç yüz kırk yedi']) assert.ok(app.includes(copy),'missing '+copy);
assert.ok(app.includes("const LESSON_FIRST_SKILLS=new Set(['nelMatchAttributes','number1000','compareOrder1000','numberPattern1000','oddEven1000'])")); assert.ok(app.includes("if(!lessonFirst&&readiness)"),'number1000 must not open with a readiness quiz'); assert.ok(app.includes('lessonTaughtAt'));
assert.ok(app.includes("$('.lesson-place-column').forEach"),'place-value teaching must bind all three concrete place-value columns');
assert.ok(!app.includes('SINGAPUR P2 ·'),'child UI must not expose curriculum-engine jargon');
assert.ok(!app.includes("?'Birleştir':step.kind==='read-write'?'Okunuşunu göster':'Değerleri keşfet'"),'place-value lesson must not present a misleading action button');
assert.ok(app.includes("renderLessonFlowFeedback"),'number1000 application must use in-context lesson feedback');
assert.ok(app.includes("return next?'sonraki adım':'oturumu tamamla';"),'lesson navigation must not call every step a question');
assert.match(css,/\.lesson-step-stage/); assert.match(css,/\.lesson-bundle-demo/); assert.match(css,/\.lesson-place-columns/);
console.log('MOE P2 number1000 teaching tests: PASS (1.1 → 1.2 → 1.3 + canonical sequence)');

assert.ok(app.includes('const NUMBER1000_LESSON_VERSION=6'),'lesson revision must invalidate stale unfinished local lesson state');
assert.ok(app.includes("lessonVersion!==NUMBER1000_LESSON_VERSION"),'stale lesson progress must be replayed in the new lesson structure');
assert.ok(app.includes("BİRLİKTE UYGULA"),'guided work must be framed as application, not another quiz');
assert.ok(app.includes("KENDİN DENE"),'independent check stage must remain explicit');
assert.ok(app.includes("$('#practiceCounter').textContent=`BİRLİKTE ${at+1} / ${Math.max(1,guided.length)}`"),'header must use stage progress rather than global question count');

assert.ok(app.includes('lesson-reveal-card'),'bundle result itself must be the reveal target');
assert.ok(app.includes('lesson-insight'),'mathematical conclusion must live inside the central teaching visual');
assert.ok(app.includes('lesson-place-arrow'),'place-value digit-to-quantity arrows must be present');
assert.ok(app.includes('lesson-word-reveal'),'number reading must reveal word parts directly');
assert.ok(app.includes('lesson-word-build'),'MOE read/write objective must include digital word construction');
assert.ok(!app.includes('id="lessonStepAction"'),'reference lesson must not depend on detached reveal buttons');
assert.match(css,/\.lesson-insight/);
assert.match(css,/\.lesson-word-build/);

for(const copy of ['Onar onar 100’e kadar sayalım.','Yüzer yüzer 1000’e kadar sayalım.','10 sıra × 10 nokta = 100 nokta','3 yüzlük + 4 onluk + 7 birlik = 347','304 = 3 yüzlük + 0 onluk + 4 birlik']) assert.ok(app.includes(copy),'missing research-backed teaching content: '+copy);
assert.ok(app.includes("const NUMBER1000_SECTIONS=['GRUPLA','SAY','KUR','BASAMAK','OKU / YAZ']"),'semantic lesson sections must be explicit');
assert.ok(app.includes('lesson-count-token'),'counting must happen on the base-ten objects themselves');
assert.ok(app.includes('lesson-hundred-sense'),'size-of-100 experience must be present');
assert.ok(app.includes('lesson-model-build'),'model-to-number transition must be taught');
assert.ok(app.includes('lesson-zero-gap'),'zero placeholder must be taught as an actually empty place');
assert.match(css,/\.lesson-section-track/); assert.match(css,/\.lesson-count-grid/); assert.match(css,/\.lesson-zero-demo/);

assert.ok(app.includes("<span>1 '+esc(step.unitName)+'</span>"),'count cards must name the unit, not cumulative totals');
assert.ok(app.includes('lesson-insight'),'lesson conclusion must live inside the central teaching visual');
assert.ok(!app.includes('lesson-core-equation'),'detached connection panel must be removed');
assert.ok(app.includes('Bir sırada 10 nokta var.'),'100-dot lesson must reveal structure in stages');
assert.ok(app.includes('lesson-digit-slots'),'model-to-number lesson must build digits progressively');
assert.ok(app.includes('lesson-place-column'),'place value must use quantity models, not label-only cards');
assert.ok(app.includes("addEventListener('pointerdown'"),'word writing must support pointer drag');
assert.ok(app.includes("dropTargetAtPoint('.lesson-word-slot'"),'word drag must resolve drop targets with touch-safe geometry');
assert.ok(app.includes('getBoundingClientRect()'),'drag target resolution must use element bounds');
assert.match(css,/\.lesson-insight/); assert.match(css,/\.lesson-place-columns/); assert.match(css,/\.lesson-word-slot/);
